### ISSUE TITLE
或计划添加大文件存储功能

### ISSUE THREAD

**Issue by LGKKY** [DCTewi/VirtualGroupEx#10]
现在常用的就是OneDrive套个壳的方案进行共享（？）
用了OneDrive或许就可以接入自动录播同步到工作表等等云云

当然也后续也可计划接入比如 阿里云OSS 腾讯云COS AWS S3等知名云存储（

**Comment by DCTewi** [comment]
不计划，工作表就是工作表。不过暑假打算单独弄一个组内用的OSS客户端。
